"""Multi-language and multi-country localization for AgentMagnet — TRULY GLOBAL.

CRITICAL: Language does NOT equal country. 'en' = 20+ countries (us, uk, au, in...).
'country' parameter MUST be used for store selection. Language is for UI/text only."""

LANGUAGES = {
    "en":    {"name": "English",    "native": "English",    "currency": "USD",  "region": "Americas"},
    "es":    {"name": "Spanish",    "native": "Espanol",    "currency": "EUR",  "region": "Europe"},
    "fr":    {"name": "French",     "native": "Francais",   "currency": "EUR",  "region": "Europe"},
    "de":    {"name": "German",     "native": "Deutsch",    "currency": "EUR",  "region": "Europe"},
    "it":    {"name": "Italian",    "native": "Italiano",   "currency": "EUR",  "region": "Europe"},
    "pt":    {"name": "Portuguese", "native": "Portugues",  "currency": "BRL",  "region": "Americas"},
    "ja":    {"name": "Japanese",   "native": "Nihongo",    "currency": "JPY",  "region": "Asia"},
    "zh":    {"name": "Chinese",    "native": "Zhongwen",   "currency": "CNY",  "region": "Asia"},
    "ko":    {"name": "Korean",     "native": "Hangugo",    "currency": "KRW",  "region": "Asia"},
    "ar":    {"name": "Arabic",     "native": "Arabiya",    "currency": "AED",  "region": "Middle East"},
    "hi":    {"name": "Hindi",      "native": "Hindi",      "currency": "INR",  "region": "Asia"},
    "nl":    {"name": "Dutch",      "native": "Nederlands", "currency": "EUR",  "region": "Europe"},
    "sv":    {"name": "Swedish",    "native": "Svenska",    "currency": "SEK",  "region": "Europe"},
    "pl":    {"name": "Polish",     "native": "Polski",     "currency": "PLN",  "region": "Europe"},
    "tr":    {"name": "Turkish",    "native": "Turkce",     "currency": "TRY",  "region": "Europe/Asia"},
    "th":    {"name": "Thai",       "native": "Phasa Thai", "currency": "THB",  "region": "Asia"},
    "vi":    {"name": "Vietnamese", "native": "Tieng Viet", "currency": "VND",  "region": "Asia"},
    "id":    {"name": "Indonesian", "native": "Bahasa Indonesia", "currency": "IDR", "region": "Asia"},
    "ms":    {"name": "Malay",      "native": "Bahasa Melayu", "currency": "MYR",  "region": "Asia"},
    "tl":    {"name": "Filipino",   "native": "Tagalog",    "currency": "PHP",  "region": "Asia"},
    "ru":    {"name": "Russian",    "native": "Russkiy",    "currency": "RUB",  "region": "Europe/Asia"},
    "uk":    {"name": "Ukrainian",  "native": "Ukrainska",  "currency": "UAH",  "region": "Europe"},
    "he":    {"name": "Hebrew",     "native": "Ivrit",      "currency": "ILS",  "region": "Middle East"},
    "el":    {"name": "Greek",      "native": "Ellinika",   "currency": "EUR",  "region": "Europe"},
    "cs":    {"name": "Czech",      "native": "Cestina",    "currency": "CZK",  "region": "Europe"},
    "ro":    {"name": "Romanian",   "native": "Romana",     "currency": "RON",  "region": "Europe"},
    "hu":    {"name": "Hungarian",  "native": "Magyar",     "currency": "HUF",  "region": "Europe"},
    "da":    {"name": "Danish",     "native": "Dansk",      "currency": "DKK",  "region": "Europe"},
    "fi":    {"name": "Finnish",    "native": "Suomi",      "currency": "EUR",  "region": "Europe"},
    "nb":    {"name": "Norwegian",  "native": "Norsk",      "currency": "NOK",  "region": "Europe"},
    "bn":    {"name": "Bengali",    "native": "Bangla",     "currency": "BDT",  "region": "Asia"},
    "ta":    {"name": "Tamil",      "native": "Tamil",      "currency": "INR",  "region": "Asia"},
    "te":    {"name": "Telugu",     "native": "Telugu",     "currency": "INR",  "region": "Asia"},
    "mr":    {"name": "Marathi",    "native": "Marathi",    "currency": "INR",  "region": "Asia"},
    "ur":    {"name": "Urdu",       "native": "Urdu",       "currency": "AED",  "region": "Asia"},
    "sw":    {"name": "Swahili",    "native": "Kiswahili",  "currency": "TZS",  "region": "Africa"},
    "ha":    {"name": "Hausa",      "native": "Hausa",      "currency": "NGN",  "region": "Africa"},
    "yo":    {"name": "Yoruba",     "native": "Yoruba",     "currency": "NGN",  "region": "Africa"},
    "ig":    {"name": "Igbo",       "native": "Igbo",       "currency": "NGN",  "region": "Africa"},
    "am":    {"name": "Amharic",    "native": "Amarinya",   "currency": "ETB",  "region": "Africa"},
    "fa":    {"name": "Persian",    "native": "Farsi",      "currency": "IRR",  "region": "Middle East"},
    "km":    {"name": "Khmer",      "native": "Phiesa Khemaer", "currency": "KHR",  "region": "Asia"},
    "lo":    {"name": "Lao",        "native": "Phasa Lao",  "currency": "LAK",  "region": "Asia"},
    "my":    {"name": "Burmese",    "native": "Myanmasa",   "currency": "MMK",  "region": "Asia"},
    "mn":    {"name": "Mongolian",  "native": "Mongol",     "currency": "MNT",  "region": "Asia"},
    "ne":    {"name": "Nepali",     "native": "Nepali",     "currency": "NPR",  "region": "Asia"},
    "si":    {"name": "Sinhala",    "native": "Sinhala",    "currency": "LKR",  "region": "Asia"},
    "ka":    {"name": "Georgian",   "native": "Kartuli",    "currency": "GEL",  "region": "Europe/Asia"},
    "hy":    {"name": "Armenian",   "native": "Hayeren",    "currency": "AMD",  "region": "Europe/Asia"},
    "az":    {"name": "Azerbaijani","native": "Azerbaycan", "currency": "AZN",  "region": "Europe/Asia"},
    "kk":    {"name": "Kazakh",     "native": "Kazaksha",   "currency": "KZT",  "region": "Asia"},
    "uz":    {"name": "Uzbek",      "native": "Ozbek",      "currency": "UZS",  "region": "Asia"},
    "ceb":   {"name": "Cebuano",    "native": "Cebuano",    "currency": "PHP",  "region": "Asia"},
    "ps":    {"name": "Pashto",     "native": "Pashto",     "currency": "AFN",  "region": "Asia"},
    "sd":    {"name": "Sindhi",     "native": "Sindhi",     "currency": "PKR",  "region": "Asia"},
    "ku":    {"name": "Kurdish",    "native": "Kurdi",      "currency": "IQD",  "region": "Middle East"},
    "tg":    {"name": "Tajik",      "native": "Tojiki",     "currency": "TJS",  "region": "Asia"},
    "tk":    {"name": "Turkmen",    "native": "Turkmen",    "currency": "TMT",  "region": "Asia"},
    "dv":    {"name": "Divehi",     "native": "Divehi",     "currency": "MVR",  "region": "Asia"},
    "ti":    {"name": "Tigrinya",   "native": "Tigrinya",   "currency": "ERN",  "region": "Africa"},
    "so":    {"name": "Somali",     "native": "Soomaali",   "currency": "SOS",  "region": "Africa"},
    "zu":    {"name": "Zulu",       "native": "isiZulu",    "currency": "ZAR",  "region": "Africa"},
    "xh":    {"name": "Xhosa",      "native": "isiXhosa",   "currency": "ZAR",  "region": "Africa"},
    "mg":    {"name": "Malagasy",   "native": "Malagasy",   "currency": "MGA",  "region": "Africa"},
    "rw":    {"name": "Kinyarwanda","native": "Ikinyarwanda","currency": "RWF",  "region": "Africa"},
    "ny":    {"name": "Chichewa",   "native": "Chichewa",   "currency": "MWK",  "region": "Africa"},
    "st":    {"name": "Sesotho",    "native": "Sesotho",    "currency": "LSL",  "region": "Africa"},
    "sn":    {"name": "Shona",      "native": "chiShona",   "currency": "ZWL",  "region": "Africa"},
    "mt":    {"name": "Maltese",    "native": "Malti",      "currency": "EUR",  "region": "Europe"},
    "lb":    {"name": "Luxembourgish","native":"Letzebuergesch", "currency": "EUR",  "region": "Europe"},
    "fy":    {"name": "Frisian",    "native": "Frysk",      "currency": "EUR",  "region": "Europe"},
    "mi":    {"name": "Maori",      "native": "Te Reo",     "currency": "NZD",  "region": "Oceania"},
    "sm":    {"name": "Samoan",     "native": "Gagana Samoa","currency": "WST",  "region": "Oceania"},
    "to":    {"name": "Tongan",     "native": "Lea Faka-Tonga","currency":"TOP",  "region": "Oceania"},
    "fj":    {"name": "Fijian",     "native": "Na Vosa Vakaviti","currency":"FJD", "region": "Oceania"},
    "ht":    {"name": "Haitian Creole","native":"Kreyol",  "currency": "HTG",  "region": "Americas"},
    "gn":    {"name": "Guarani",    "native": "Ava Nee",    "currency": "PYG",  "region": "Americas"},
    "ay":    {"name": "Aymara",     "native": "Aymar",      "currency": "BOB",  "region": "Americas"},
    "qu":    {"name": "Quechua",    "native": "Runa Simi",  "currency": "PEN",  "region": "Americas"},
    "mfe":   {"name": "Mauritian Creole","native":"Kreol Morisien", "currency": "MUR",  "region": "Africa"},
    "sg":    {"name": "Sango",      "native": "Sango",      "currency": "XAF",  "region": "Africa"},
    "rn":    {"name": "Kirundi",    "native": "Ikirundi",   "currency": "BIF",  "region": "Africa"},
    "lg":    {"name": "Luganda",    "native": "Luganda",    "currency": "UGX",  "region": "Africa"},
    "om":    {"name": "Oromo",      "native": "Afaan Oromo","currency": "ETB",  "region": "Africa"},
    "tw":    {"name": "Twi",        "native": "Twi",        "currency": "GHS",  "region": "Africa"},
}

AMAZON_STORES = {
    "com":    {"domain": "amazon.com",     "country": "United States",   "lang": "en", "currency": "USD", "region": "Americas"},
    "co.uk":  {"domain": "amazon.co.uk",   "country": "United Kingdom",  "lang": "en", "currency": "GBP", "region": "Europe"},
    "de":     {"domain": "amazon.de",      "country": "Germany",         "lang": "de", "currency": "EUR", "region": "Europe"},
    "fr":     {"domain": "amazon.fr",      "country": "France",          "lang": "fr", "currency": "EUR", "region": "Europe"},
    "it":     {"domain": "amazon.it",      "country": "Italy",           "lang": "it", "currency": "EUR", "region": "Europe"},
    "es":     {"domain": "amazon.es",      "country": "Spain",           "lang": "es", "currency": "EUR", "region": "Europe"},
    "co.jp":  {"domain": "amazon.co.jp",   "country": "Japan",           "lang": "ja", "currency": "JPY", "region": "Asia"},
    "ca":     {"domain": "amazon.ca",      "country": "Canada",          "lang": "en", "currency": "CAD", "region": "Americas"},
    "com.au": {"domain": "amazon.com.au",  "country": "Australia",       "lang": "en", "currency": "AUD", "region": "Oceania"},
    "in":     {"domain": "amazon.in",      "country": "India",           "lang": "en", "currency": "INR", "region": "Asia"},
    "com.mx": {"domain": "amazon.com.mx",  "country": "Mexico",          "lang": "es", "currency": "MXN", "region": "Americas"},
    "com.br": {"domain": "amazon.com.br",  "country": "Brazil",          "lang": "pt", "currency": "BRL", "region": "Americas"},
    "nl":     {"domain": "amazon.nl",      "country": "Netherlands",     "lang": "nl", "currency": "EUR", "region": "Europe"},
    "se":     {"domain": "amazon.se",      "country": "Sweden",          "lang": "sv", "currency": "SEK", "region": "Europe"},
    "pl":     {"domain": "amazon.pl",      "country": "Poland",          "lang": "pl", "currency": "PLN", "region": "Europe"},
    "ae":     {"domain": "amazon.ae",      "country": "UAE",             "lang": "ar", "currency": "AED", "region": "Middle East"},
    "sa":     {"domain": "amazon.sa",      "country": "Saudi Arabia",    "lang": "ar", "currency": "SAR", "region": "Middle East"},
    "sg":     {"domain": "amazon.sg",      "country": "Singapore",       "lang": "en", "currency": "SGD", "region": "Asia"},
    "tr":     {"domain": "amazon.com.tr",  "country": "Turkey",          "lang": "tr", "currency": "TRY", "region": "Europe/Asia"},
    "com.be": {"domain": "amazon.com.be",  "country": "Belgium",         "lang": "nl", "currency": "EUR", "region": "Europe"},
    "eg":     {"domain": "amazon.eg",      "country": "Egypt",           "lang": "ar", "currency": "EGP", "region": "Africa"},
    "cn":     {"domain": "amazon.cn",      "country": "China",           "lang": "zh", "currency": "CNY", "region": "Asia"},
}

EBAY_STORES = {
    "com":    {"domain": "ebay.com",     "country": "United States",    "lang": "en", "currency": "USD", "region": "Americas"},
    "co.uk":  {"domain": "ebay.co.uk",   "country": "United Kingdom",   "lang": "en", "currency": "GBP", "region": "Europe"},
    "de":     {"domain": "ebay.de",      "country": "Germany",          "lang": "de", "currency": "EUR", "region": "Europe"},
    "fr":     {"domain": "ebay.fr",      "country": "France",           "lang": "fr", "currency": "EUR", "region": "Europe"},
    "it":     {"domain": "ebay.it",      "country": "Italy",            "lang": "it", "currency": "EUR", "region": "Europe"},
    "es":     {"domain": "ebay.es",      "country": "Spain",            "lang": "es", "currency": "EUR", "region": "Europe"},
    "com.au": {"domain": "ebay.com.au",  "country": "Australia",        "lang": "en", "currency": "AUD", "region": "Oceania"},
    "ca":     {"domain": "ebay.ca",      "country": "Canada",           "lang": "en", "currency": "CAD", "region": "Americas"},
    "ch":     {"domain": "ebay.ch",      "country": "Switzerland",      "lang": "de", "currency": "CHF", "region": "Europe"},
    "at":     {"domain": "ebay.at",      "country": "Austria",          "lang": "de", "currency": "EUR", "region": "Europe"},
    "be":     {"domain": "ebay.be",      "country": "Belgium",          "lang": "nl", "currency": "EUR", "region": "Europe"},
    "nl":     {"domain": "ebay.nl",      "country": "Netherlands",      "lang": "nl", "currency": "EUR", "region": "Europe"},
    "pl":     {"domain": "ebay.pl",      "country": "Poland",           "lang": "pl", "currency": "PLN", "region": "Europe"},
    "ie":     {"domain": "ebay.ie",      "country": "Ireland",          "lang": "en", "currency": "EUR", "region": "Europe"},
    "sg":     {"domain": "ebay.sg",      "country": "Singapore",        "lang": "en", "currency": "SGD", "region": "Asia"},
    "hk":     {"domain": "ebay.hk",      "country": "Hong Kong",        "lang": "zh", "currency": "HKD", "region": "Asia"},
    "my":     {"domain": "ebay.my",      "country": "Malaysia",         "lang": "ms", "currency": "MYR", "region": "Asia"},
    "ph":     {"domain": "ebay.ph",      "country": "Philippines",      "lang": "tl", "currency": "PHP", "region": "Asia"},
    "th":     {"domain": "ebay.co.th",   "country": "Thailand",         "lang": "th", "currency": "THB", "region": "Asia"},
    "vn":     {"domain": "ebay.vn",      "country": "Vietnam",          "lang": "vi", "currency": "VND", "region": "Asia"},
    "in":     {"domain": "ebay.in",      "country": "India",            "lang": "hi", "currency": "INR", "region": "Asia"},
    "il":     {"domain": "ebay.co.il",   "country": "Israel",           "lang": "he", "currency": "ILS", "region": "Middle East"},
}

AMAZON_STORE_TAG_MAP = {
    "com": "amazon_tag_us", "co.uk": "amazon_tag_uk", "de": "amazon_tag_de",
    "fr": "amazon_tag_fr", "it": "amazon_tag_it", "es": "amazon_tag_es",
    "co.jp": "amazon_tag_jp", "ca": "amazon_tag_ca", "com.au": "amazon_tag_au",
    "in": "amazon_tag_in", "com.mx": "amazon_tag_mx", "com.br": "amazon_tag_br",
    "nl": "amazon_tag_nl", "se": "amazon_tag_se", "pl": "amazon_tag_pl",
    "ae": "amazon_tag_ae", "sa": "amazon_tag_sa", "sg": "amazon_tag_sg",
    "tr": "amazon_tag_tr", "com.be": "amazon_tag_be", "eg": "amazon_tag_eg",
    "cn": "amazon_tag_cn",
}

EBAY_STORE_TAG_MAP = {
    "com": "ebay_campaign_us", "co.uk": "ebay_campaign_uk", "de": "ebay_campaign_de",
    "fr": "ebay_campaign_fr", "it": "ebay_campaign_it", "es": "ebay_campaign_es",
    "com.au": "ebay_campaign_au", "ca": "ebay_campaign_ca",
    "ch": "ebay_campaign_ch", "at": "ebay_campaign_at", "be": "ebay_campaign_be",
    "nl": "ebay_campaign_nl", "pl": "ebay_campaign_pl", "ie": "ebay_campaign_ie",
    "sg": "ebay_campaign_sg", "hk": "ebay_campaign_hk", "my": "ebay_campaign_my",
    "ph": "ebay_campaign_ph", "th": "ebay_campaign_th", "vn": "ebay_campaign_vn",
    "in": "ebay_campaign_in", "il": "ebay_campaign_il",
}

# Language → default country (fallback when country is not provided)
LANGUAGE_DEFAULT_COUNTRY = {
    "en": "us", "es": "mx", "fr": "fr", "de": "de", "it": "it",
    "pt": "br", "ja": "jp", "zh": "cn", "ko": "kr", "ar": "ae",
    "hi": "in", "nl": "nl", "sv": "se", "pl": "pl", "tr": "tr",
    "th": "th", "vi": "vn", "id": "id", "ms": "my", "tl": "ph",
    "ru": "ru", "uk": "ua", "he": "il", "el": "gr", "cs": "cz",
    "ro": "ro", "hu": "hu", "da": "dk", "fi": "fi", "nb": "no",
    "bn": "bd", "ta": "in", "te": "in", "mr": "in", "ur": "pk",
    "sw": "tz", "ha": "ng", "yo": "ng", "ig": "ng", "am": "et",
    "fa": "ir", "km": "kh", "lo": "la", "my": "mm", "mn": "mn",
    "ne": "np", "si": "lk", "ka": "ge", "hy": "am", "az": "az",
    "kk": "kz", "uz": "uz",
    "ceb": "ph", "ps": "af", "sd": "pk", "ku": "iq", "tg": "tj",
    "tk": "tm", "dv": "mv", "ti": "er", "so": "so", "zu": "za",
    "xh": "za", "mg": "mg", "rw": "rw", "ny": "mw", "st": "ls",
    "sn": "zw", "mt": "mt", "lb": "lu", "fy": "nl", "mi": "nz",
    "sm": "ws", "to": "to", "fj": "fj", "ht": "ht", "gn": "py",
    "ay": "bo", "qu": "pe", "mfe": "mu", "sg": "cf", "rn": "bi",
    "lg": "ug", "om": "et", "tw": "gh",
}


def get_amazon_store(language: str) -> str:
    from .tools.region_filter import COUNTRY_AMAZON
    default_country = LANGUAGE_DEFAULT_COUNTRY.get(language, "us")
    return COUNTRY_AMAZON.get(default_country, "com")


def get_ebay_store(language: str) -> str:
    from .tools.region_filter import COUNTRY_EBAY
    default_country = LANGUAGE_DEFAULT_COUNTRY.get(language, "us")
    return COUNTRY_EBAY.get(default_country, "com")


def get_currency(language: str) -> str:
    return LANGUAGES.get(language, LANGUAGES["en"])["currency"]


def get_language_name(language: str) -> str:
    return LANGUAGES.get(language, LANGUAGES["en"])["native"]


def get_region(language: str) -> str:
    return LANGUAGES.get(language, LANGUAGES["en"])["region"]


def detect_language(text: str) -> str:
    text = text.lower()
    lang_map = {
        "en": ["english", "united states", "united kingdom", "australia"],
        "es": ["espanol", "espanola", "espana", "mexico", "argentina", "colombia"],
        "fr": ["francais", "francaise", "france", "belgique"],
        "de": ["deutsch", "deutsche", "deutschland", "german", "oesterreich"],
        "it": ["italiano", "italiana", "italia"],
        "pt": ["portugues", "portuguesa", "brasil"],
        "ja": ["japanese", "nihongo", "japan"],
        "zh": ["chinese", "zhongwen", "china"],
        "ko": ["korean", "hangugo", "korea"],
        "ar": ["arabic", "arabiya", "arabian", "middle east"],
        "hi": ["hindi", "india"],
        "nl": ["dutch", "nederlands", "nederland"],
        "sv": ["swedish", "svenska", "sweden"],
        "pl": ["polish", "polski", "poland", "polska"],
        "tr": ["turkish", "turkce", "turkey", "turkiye"],
        "th": ["thai", "phasa thai", "thailand"],
        "vi": ["vietnamese", "tieng viet", "vietnam"],
        "id": ["indonesian", "bahasa indonesia", "indonesia"],
        "ms": ["malay", "bahasa melayu", "malaysia"],
        "tl": ["filipino", "tagalog", "philippines"],
        "ru": ["russian", "russkiy", "russia"],
        "uk": ["ukrainian", "ukrainska", "ukraine"],
        "he": ["hebrew", "ivrit", "israel"],
        "el": ["greek", "ellinika", "greece"],
        "cs": ["czech", "cestina", "czech republic"],
        "ro": ["romanian", "romana", "romania"],
        "hu": ["hungarian", "magyar", "hungary"],
        "da": ["danish", "dansk", "denmark"],
        "fi": ["finnish", "suomi", "finland"],
        "nb": ["norwegian", "norsk", "norway"],
        "bn": ["bengali", "bangla", "bangladesh"],
        "ta": ["tamil", "tamil nadu"],
        "te": ["telugu", "andhra"],
        "mr": ["marathi", "maharashtra"],
        "ur": ["urdu", "pakistan"],
        "sw": ["swahili", "kiswahili", "tanzania", "kenya"],
        "ha": ["hausa", "nigeria", "niger"],
        "yo": ["yoruba", "nigeria"],
        "ig": ["igbo", "nigeria"],
        "am": ["amharic", "amarinya", "ethiopia"],
        "fa": ["persian", "farsi", "iran"],
        "km": ["khmer", "cambodia"],
        "lo": ["lao", "laos"],
        "my": ["burmese", "myanmar"],
        "mn": ["mongolian", "mongol", "mongolia"],
        "ne": ["nepali", "nepal"],
        "si": ["sinhala", "sri lanka"],
        "ka": ["georgian", "kartuli", "georgia"],
        "hy": ["armenian", "hayeren", "armenia"],
        "az": ["azerbaijani", "azerbaijan"],
        "kk": ["kazakh", "kazakhstan"],
        "uz": ["uzbek", "uzbekistan"],
        "ceb": ["cebuano", "cebu", "visayan"],
        "ps": ["pashto", "pashtun", "afghanistan"],
        "sd": ["sindhi", "sindh"],
        "ku": ["kurdish", "kurdi", "kurdistan"],
        "tg": ["tajik", "tojiki", "tajikistan"],
        "tk": ["turkmen", "turkmenistan"],
        "dv": ["divehi", "dhivehi", "maldives"],
        "ti": ["tigrinya", "eritrea", "ethiopia"],
        "so": ["somali", "soomaali", "somalia"],
        "zu": ["zulu", "isizulu", "south africa"],
        "xh": ["xhosa", "isixhosa", "south africa"],
        "mg": ["malagasy", "madagascar"],
        "rw": ["kinyarwanda", "rwanda"],
        "ny": ["chichewa", "malawi"],
        "st": ["sesotho", "lesotho"],
        "sn": ["shona", "zimbabwe"],
        "mt": ["maltese", "malta"],
        "lb": ["luxembourgish", "luxembourg"],
        "fy": ["frisian", "frysk", "netherlands"],
        "mi": ["maori", "new zealand", "aotearoa"],
        "sm": ["samoan", "samoa"],
        "to": ["tongan", "tonga"],
        "fj": ["fijian", "fiji"],
        "ht": ["haitian", "creole", "kreyol", "haiti"],
        "gn": ["guarani", "paraguay"],
        "ay": ["aymara", "bolivia", "peru"],
        "qu": ["quechua", "peru", "bolivia", "ecuador"],
        "mfe": ["mauritian", "kreol", "mauritius"],
        "sg": ["sango", "central african republic"],
        "rn": ["kirundi", "burundi"],
        "lg": ["luganda", "uganda"],
        "om": ["oromo", "afaan oromo", "ethiopia"],
        "tw": ["twi", "ghana", "akan"],
    }
    for code, keywords in lang_map.items():
        if any(kw in text for kw in keywords):
            return code
    return "en"
